### ISSUE TITLE
URGENT 2.37.3 fails to complete its build - building 2.37.2 works fine - cause of problem found - missing file

### ISSUE THREAD

**Issue by jpbion** [util-linux/util-linux#1577]
The 2.37.3 source tarball leaves out disk-utils/raw.8

Because of this, the typical make of util-linux requires that any system building util-linux contain the ability to convert asciidoc files to manual pages. If that support is missing (as it is on my system), the build will fail before completion, noticing there is no rule to convert from adoc to man. 

I noted this as URGENT in the title not because I am alarmist, but since 2.37.3 is a security release, I figure you'd want to get this issue fixed for all the people trying to build util-linux who don't happen to have a way to convert adoc to a man page.

**Comment by karelzak** [comment]
Install asciidoctor or use --disable-raw

The reason is that the tarball has been generated on the system without raw support, so pre-generated man pages do not include raw.8. Note that raw is not supported by recent kernels and it is a deprecated tool.

**Comment by jpbion** [comment]
Fair enough, but then shouldn’t raw support be disabled by default  in this package?

**Comment by karelzak** [comment]
For now, there is UL_DEFAULT_ENABLE([raw], [check]), so it checks for /usr/include/linux/raw.h and if accessible then enable raw support. The problem is that I have generated the tarball on the system without this header file and you have a system with it ;-)

The next v2.38 will be robust enough to generate the man pages for the tarball independently on any external conditions.

Sorry, for this stupid bug. Fortunately, --disable-raw is a good workaround for everyone.
