### ISSUE TITLE
terminal-colors.d client applications

### ISSUE THREAD

**Issue by bobOnGitHub** [util-linux/util-linux#1593]
Hi,

I'd like to make a suggestion.

It might make sense to advise application developers/maintainers using/conforming to terminal-colors.d to

1. Not apply any hard coded default colours and in the absence of a colours file leave all output uncoloured by default.
2. Optionally supply default colours in a file for inclusion in /etc/terminal-colors.d as part of the install process.
3. Comment the file at point 2 so end users can understand it.

This 
1. removes any necessity to document default colours in man pages or elsewhere.
2. reduces application code.
3. removes confusion for end users and avoids leading them into code to figure out what colours mean.

See [here](https://forums.rockylinux.org/t/nmcli-output-color-mapping/5274?u=bobar) as an example of what could be avoided.

**Comment by karelzak** [comment]
No ;-) 

Please, for the years the default in all our tools is to make things usable without config files and make it usable for the majority of users. That's the goal. 

And because we want to be friendly to users with different requirements (color-blind people, etc.) we have introduced a simple solution to disable all the colors in all the tools by one simple "touch /etc/terminal-colors.d/disable" command.

It does not make sense to force the majority of users to install and maintain some config files if only a small subset of users can disable the colors with one "touch" command.

And finally, if you (or your distro) don't like enabled colors by default you can compile util-linux with --disable-colors-default.

I think the current solution is fair enough and keeps things usable for color-blind people, etc

What I see is an opportunity to improve documentation, there should be at the beginning of terminal-colors.d(5) and in individual tools information (example) how to disable the colors. I'll do it.

**Comment by bobOnGitHub** [comment]
FOR THE LOVE OF GOD ! This is why SW is the way it is today....

I've spent 4 months trying to put together a usable VIABLE linux alternative to windows and I've been in software development for over 30yrs so I know wtf I'm talking about...

>Please, for the years the default in all our tools is to make things usable without config files and **make it usable for the majority of users.** That's the goal.

I'm trying to help you with that.

>And because we want to be friendly to users with different requirements (color-blind people, etc.) we have introduced a simple solution to disable all the colors in all the tools by one simple "touch /etc/terminal-colors.d/disable" command.

 which my recommendations would not affect.

>It does not make sense to force the majority of users to install and maintain some config files

I'm not suggesting you should - I suggested the developer supply the default as a config file rather that hard code it.

>...if only a small subset of users can disable the colors with one touch command.

 ... THEY HAVE TO DO THAT NOW ANYWAY.

>And finally, if you (or your distro) don't like enabled colors by default you can compile util-linux with --disable-colors-default. - 

I'm a user not a distro developer and in case you hadn't noticed, building sw on linux is rarely trivial besides which I won't know if the developer stuck to the rules and (based on experience) will likely waste a significant amount of time to find out he didn't or there is some other issue to be resolved.

>I think the current solution is fair enough and keeps things usable for color-blind people, etc

 NO IT DOESN'T - where the colours are hard coded and they don't want them they have to alter config files anyway. My way gives them 2 options , in fact it gives them a more intuitive option: delete the colour file which will occur to most people before "touch" a disable file.

>What I see is an opportunity to improve documentation, there should be at the beginning of terminal-colors.d(5) and in individual tools information (example) how to disable the colors. I'll do it.

What I see is someone who misread/didn't read the issue, gave a completely inappropriate response, and junked an opportunity to do things in the most sensible , practical , sustainable, simple way possible... AND was infuriatingly sarky and dismissive about it.... being wrong, sarky and dismissive..... wow!
