### ISSUE TITLE
[Q] su command: why pam_get_username didn't used

### ISSUE THREAD

**Issue by sulincix** [util-linux/util-linux#1608]
Why pam_get_username command didn't used for getting username from pam?

https://linux.die.net/man/3/pam_get_user

**Comment by sulincix** [comment]
https://github.com/util-linux/util-linux/blob/master/lib/pwdutils.c#L28

**Comment by karelzak** [comment]
Because PAM is not initialized in time we need the username (and passwd data). There is also necessary to use the username for pam_start(), so I do not see a way how to avoid getpwdnam().

Maybe we can after successful authentication re-read the username (as login(1) does), but not sure if we really need it.

Why do you ask for it? :-)
