### ISSUE TITLE
lsblk: json output format is incorrect in 2.38 version

### ISSUE THREAD

**Issue by akhiljalagam** [util-linux/util-linux#1636]
`$ lsblk -OJ | jq -r '.blockdevices[]'`
parse error: Invalid numeric literal at line 66, column 23

`line 66, column 23`

```
         "zone-sz": 0B,
         "zone-wgran": 0B,
         "zone-app": 0B,
         "zone-nr": 0,
         "zone-omax": 0,
         "zone-amax": 0,
```

`0B` should be quoted.

**Comment by karelzak** [comment]
Good catch, Thanks!

A possible workaround (until v2.38.1 will be available) is to use --bytes, this option forces lsblk to use numbers instead of human-readable sizes.

**Comment by SimonFair** [comment]
> Good catch, Thanks!
> 
> A possible workaround (until v2.38.1 will be available) is to use --bytes, this option forces lsblk to use numbers instead of human-readable sizes.

Is there a timeline for 2.38.1?

**Comment by karelzak** [comment]
Good question, I'd like to have 2.38.1 in the next 14 days.

**Comment by karelzak** [comment]
Released.

**Comment by gerow** [comment]
@karelzak this seems to have changed lsblk's behavior in the `--bytes` case. Where previously `fsavail` was a string (as were presumably `fssize` and `fsused`) they are not represented as u64s.

So in v2.38:

```
# lsblk --all --bytes --output-all --json 
...
               "fsavail": "1339809792",
...
```

But in v2.38.1:

```
# lsblk --all --bytes --output-all --json 
...
               "fsavail": 1339809792,
...
```

Which of course parses, but it means that tools that were previously expecting a string there will fail, like using go's ability to parse json into struct fields.

```
FSAvail string `json:"fsavail"`
```

Of course, a number makes plenty of sense here, so changing the parsing on my side is easy, but just wanted to bring this up here in case that wasn't intended since I expect it might impact others.

**Comment by karelzak** [comment]
Yes, this is expected, although it introduces backward incompatibility.

**Comment by tigerinus** [comment]
> Yes, this is expected, although it introduces backward incompatibility.



Our project depends on the JSON output from `lsblk`. We have no way to force the version of `lsblk` installed for our users. 

This string -> number change is a breaking change for us. 

Would it be OK to revert to the original behavior?

Thanks!

**Comment by karelzak** [comment]
If we revert the change, we will forever use the three numbers as strings. Is it wanted? For example, the old version is able to produce:
```JSON
{
         "fsavail": "39843893248",
         "size": 46037278208
 }
```
it's pretty inconsistent. 

I have no clue about your project, but can you not accept both ways or modify the JSON string before it's parsed to remove the quotes for fsavail, fssize, fsused ?

(Sorry for the pain ...)

**Comment by tigerinus** [comment]
Given that util-linux package is such critical in every domain, that millions of disk management related scripts from cloud to IoT might be using it, I think breaking change should be taken care of more carefully to minimize the impact.

Perfect is the enemy of good.

**Comment by socketpair** [comment]
Actually, there is no restriction on integers in JSON. There is in JavaScript. For example, Python reads big integers (i.e. ever more than 64 bit) easily from JSON. There should be a switch for the way integers are represented in JSONs. As a number by default, and as a string if enabled explicitly.

P.S. The bug triggered our solution. In general, it's better to use some JSON serialization library instead of `printf`. Or at least, make some tests.

**Comment by karelzak** [comment]
> Actually, there is no restriction on integers in JSON. There is in JavaScript. For example, Python reads big integers (i.e. ever more than 64 bit) easily from JSON. There should be a switch for the way integers are represented in JSONs. As a number by default, and as a string if enabled explicitly.

I like this idea; we can make it possible to control how numbers are printed in the JSON output, for example, adding environment variables, etc.

> P.S. The bug triggered our solution. In general, it's better to use some JSON serialization library instead of `printf`. Or at least, make some tests.

Well, there is a simple API (and code) in the package to print JSON. You're right that adding more tests would be a good solution. There are some tests, but it's always util-specific (sfdisk, lsmem, etc.), add something more generic would be nice. I'll do it.

**Comment by karelzak** [comment]
BTW, the problem was not in the serialization code, but that the values have not been marked as numbers in lsblk.
