### ISSUE TITLE
util-linux cannot be cross compiled with meson

### ISSUE THREAD

**Issue by neheb** [util-linux/util-linux#1671]
```
meson.build:580:0: ERROR: Can not run test applications in this cross environment.
```

run() cannot be used.

ping @eli-schwartz

**Comment by eli-schwartz** [comment]
`cc.run()` requires specifying an exe_wrapper (e.g. qemu) in your cross compile environment file, in order to actually execute the produced test executable as requested.

You may of course ask @keszybz (who implemented the meson build) why the build system needs to *run* a binary in order to acquire configuration-time information. I'm sure it was believed to be necessary at the time. And maybe that's true and it is needed. On the other hand, maybe it's not, and can be done in an easier to cross-compile manner. In some use cases, the former will be true, while in other use cases, the latter will be true.

Personally, I have no idea. I haven't looked at what `cc.run()` is being used for, or whether it can be rewritten differently. It wasn't the focus of the only build system modifications I've done here.

**Comment by neheb** [comment]
There's no need to run it. I'll whip up a PR.

**Comment by karelzak** [comment]
I have applied @neheb's PR and it works for me. Closing.
