### ISSUE TITLE
dmesg: Add sub-second timestamp support for `--since` and `--until`

### ISSUE THREAD

**Issue by opty77** [util-linux/util-linux#1708]
Please add sub-second timestamp support for `--since` and `--until`.

**Comment by sdshlanta** [comment]
Upon some investigation, it would appear that the difficulty in this request caused by a limitation of the method used by `dmesg` (and it would appear `util-linux` as a whole) to parse time values from strings.

Under the hood it uses `strptime` to much of the heavy lifting.  `strptime` only returns results down to the second.  The simplest way to implement this would be to add some sort of `--since-ms` and `--until-ms` parameters that could be suppled in conjunction with `--since` and `--until` but that would be less than elegant.
