### ISSUE TITLE
Clarify licenses for common includes used by libuuid.

### ISSUE THREAD

**Issue by JamesMBartlett** [util-linux/util-linux#2010]
It seems to me like the intention is for all of libuuid to be licensed under BSD-3. However, some of the common headers included by libuuid (eg. strutils.h, randutils.h, md5.h, and nls.h) don't have any licensing information in the file. Based on the top level README.licensing, the absence of licensing info in the file means they are under GPL2 or later. As far as I'm aware, this would mean that all of libuuid would be subject to the requirements of GPL2 or later. I don't think this is the intention so some clarity here would be much appreciated.

**Comment by karelzak** [comment]
Ah, it seems the include/ directory needs the same live as lib/ ;-)

The bug is that the header files in the include/ do not copy license statement from relevant code from lib/; for example, strutils.c is public domain (so strutils.h should be too), the same md5, randutils is BSD.

I'll fix it tomorrow. Thanks for your report.

**Comment by JamesMBartlett** [comment]
Thanks for the speedy fix.
