### ISSUE TITLE
fdisk: Add support for the Linux luks encrypted device GPT partition type:

### ISSUE THREAD

**Issue by 05storm26** [util-linux/util-linux#2073]
Hi,

Currently fdisk shows the GPT partition type: CA7D7CCB-63ED-4C53-861C-1742536059CC as "unknown".

Could you add it as a GPT partition type?

**Comment by karelzak** [comment]
Hi, 

What version of fdisk are you using? This type has been there since commit 5aa8d13b13 (v2.27, Sep 2015).

**Comment by 05storm26** [comment]
It's archlinux:

```
fdisk from util-linux 2.38.1
```

```
$ sudo fdisk -l /dev/sda
Disk /dev/sda: xxx GiB, xxxx bytes, xxxxx sectors
Disk model: SAMSUNG MZNLN256
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: xxxxxxxxxx

Device         Start       End   Sectors  Size Type
/dev/sda1       x   xxx   xxx    3G EFI System
/dev/sda2    xxxx xxxxx xxxx  220G unknown
/dev/sda3  xxxxx xxxxx  xxxx 15.3G Linux swap
````

gdisk says:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            xxxx         xxxx   3.0 GiB     EF00  Linux filesystem
   2         xxxx       xxxx   220.0 GiB   8309  Linux LUKS
   3       xxxx       xxx   15.3 GiB    8200  
```

**Comment by 05storm26** [comment]
Actually looking at the code you linked the GUID for LUKS ("CA7D7CCB-63ED-4C53-861C-1742536059CC") is commented out with the comment "too crazy, ignore for now:". Not sure why.

**Comment by karelzak** [comment]
Ah, sorry (my vim(1) uses the same color for all strings, although it's commented out). 

Yes, I remember it. LUKS maintainer does not like it -- for the Linux kernel, the partition types have no meaning, and people who use LUKS should not be forced to use any explicit partition type. A little bit different situation is, for example, some logic in systemd where partition could be used according to GPT type. However, you can still detect the partition's content to make a decision for automation. 

@mbroz any objection & comment about LUKS gpt partition type? ;-)

**Comment by 05storm26** [comment]
So what is the recommendation? Just use the "Linux partition" GPT type?

**Comment by karelzak** [comment]
> So what is the recommendation? Just use the "Linux filesystem" GPT type?

Yes, just like for other stuff.

**Comment by TriMoon** [comment]
@05storm26 The ability for the user to use any filesystem inside a partition is something completely different as the requirement for a filesystem to be of certain partition type.

So although we can use any partition type to create a LUKS volume inside, the user can have reasons why it want's to mark such partitions as LUKS for it's use.
At least i **want** to mark my LUKS2 partition as such, because i have multiple OS's installed and want to easily find the partition to cross mount when listing the partitions, because i tend to forget which partition was what on some disks, especially when a few months or more have past.

If your intention, by not supporting this GUID, is to make people use other tools instead and thus make your tool obsolete that's up to you...
But i would request you to add/enable this GUID for us, giving the user the freedom to use it or not.
