### ISSUE TITLE
losetup sometimes opens /dev/loopN with O_RDONLY when configuring loop device

### ISSUE THREAD

**Issue by marmarek** [util-linux/util-linux#2434]
When loop device is configured (`losetup /dev/loop0 /some/file`), sometimes `losetup` opens the loop device with `O_RDONLY`. Udev watches for `IN_CLOSE_WRITE` inotify event for loop device changes (since no uevent is produced for loop device change). But when device is opened with `O_RDONLY`,  only `IN_CLOSE_NOWRITE` inotify event being emited, and udev does not notice the change.

The `O_RDONLY` seems to be used when the target file is read-only (for example on a read-only filesystem). In such case, the loop device should be configured as read-only (`LO_FLAGS_READ_ONLY`), but the device itself should still be opened with `O_RDWR`.

If I'm not mistaken, it's [this line](https://github.com/util-linux/util-linux/blob/master/lib/loopdev.c#L1398) to change. What are the reasons for the current behavior?

**Comment by karelzak** [comment]
I guess it's because the code uses one flag for all operations. It seems we do not need LOOPDEV_FL_RDWR and LOOPDEV_FL_RDONLY at all. It's good enough to open the device always read-only and for new devices use read-write mode to keep udevd happy.

Is there any other situation when udevd needs read-write mode? (losetup --delete ?)

I'll prepare a patch.
