### ISSUE TITLE
Terminal echo injured

### ISSUE THREAD

**Issue by jidanni** [util-linux/util-linux#2708]
```
# fsck /dev/sdd1
fsck from util-linux 2.39.3
fsck.fat 4.2 (2021-01-31)
There are differences between boot sector and its backup.
This is mostly harmless. Differences: (offset:original/backup)
  65:01/00
1) Copy original to backup
2) Copy backup to original
3) No action
[123?q]?
```

OK, lets say the user just hits RETURN, and then some ^C's.

Never mind why he does this. Maybe he is lazy or uncomfortable. It
doesn't matter.

OK, now we are finally back at our shell prompt. But echo has been
turned off.

We will think our computer is broken, unless we know to use reset(1).

Anyway, if this were a shell script I would just do
```
read answer
```
That wouldn't mess up the tty echo. So please use the same simple logic
in your C program. Thanks.

**Comment by karelzak** [comment]
It's probably a bad place to report the issue. 

Fsck is just a wrapper, and it executes fsck.fat, and your interaction is with the FAT helper. Fsck itself does not modify any terminal setting.

On my system fsck.fat comes from dosfstools package.

**Comment by jidanni** [comment]
Well. You can't blame bug reporters, because the package is taking all the credit and printing its own version number and not revealing what's going on under the hood...

**Comment by karelzak** [comment]
Let's notify @pali and @ferivoz  from dosfstools project ;-)

**Comment by ferivoz** [comment]
Hello @jidanni and @karelzak,

thank you for informing me about this! I took a closer look and this happens because `fsck.fat` does not reset the terminal if CTRL+C is pressed. The e2fsprogs (fsck.ext4 etc.) only disable echo when needed. The `fsck.fat` tool from dosfstools disables echo by default and only enables it at the end again or when a longer string has to be entered, like a filesystem name.

My proposed change does not fix every single occurrence like a getpassphrase implementation would do. But it also doesn't happen in e2fsprogs either. I think a really proper solution covering all cases would take much more time, and even though it is very nice to get informed by you, Karel, I am not a maintainer of dosfstools.

You can see my pull request here: https://github.com/dosfstools/dosfstools/pull/207

Dan, could you kindly see if this version works for you?

**Comment by jidanni** [comment]
I'm sure it's a great fix, but will take time to get to Debian Sid, plus, um, "gramps shouldn't do experiments with his disks"... so: I'll trust you that it works good.
