### ISSUE TITLE
make sure lastlog2 is separated from original lastlog

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#2769]
IMHO, it's necessary to make it possible to install lastlog2 stuff to the system where it is still the original lastlog. Otherwise, it will not be possible to optionally test the library (and pam_lastlog2), and installation will be an invasive change for distributions and will require changes to other packages. 

I found:
```
cat misc-utils/lastlog2.conf
# This file is part of lastlog2.
#
# See tmpfiles.d(5) for details
#
d /var/lib/lastlog 0755 - - -
```
and
```
#define LL2_DEFAULT_DATABASE "/var/lib/lastlog/lastlog2.db"
```
It would be better to use `/var/lib/lastlog2/` as a directory name.

**Comment by t-8ch** [comment]
Note:
The non-util-linux-variant of lastlog2 used the same path, so it could break compatibility with it.
I'm not sure it's relevant, though.

**Comment by karelzak** [comment]
Well, I had the ambition to add lastlog2 to Fedora as experimental stuff (extra subpackage, optional)  and officially switch to lastlog2 later (because it will require additional steps and some "bureaucracy"). Unfortunately, for now, I have to use --disable-liblastlog2 for -rc1 because it's invasive.

**Comment by t-8ch** [comment]
It probably depends if anybody really used the original lastlog2. It seems suse used it.
Maybe @schubi2 knows where it is already used.

**Comment by thkukuk** [comment]
The original lastlog2 is used in all current openSUSE and SUSE Distributions, so it is used in many places.
But: lastlog does not use `/var/lib/lastlog`, it uses `/var/log/lastlog`. So I don't understand the problem, there is no conflict.
We did the migration on openSUSE Tumbleweed from lastlog to lastlog2 in a rolling fashion, both tools were installed and used in parallel for several month, so that the data could be automatically migrated. 
There were no issues, it's designed in a way that it works.
